### ISSUE TITLE
specs randomly dump undefined method `thread_safety' for #<Class...>

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/more_core_extensions#77]
If you run the tests with `bundle exec rspec --order random` you will occasionally get the following error in the output (but the tests don't actually fail):

```text
#<Thread:0x00007fecd012e048@/Users/jfrey/dev/more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:166 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from /Users/jfrey/dev/more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:167:in `block (4 levels) in <top (required)>'
	1: from /Users/jfrey/dev/more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:167:in `times'
/Users/jfrey/dev/more_core_extensions/spec/core_ext/module/cache_with_timeout_spec.rb:168:in `block (5 levels) in <top (required)>': undefined method `thread_safety' for #<Class:0x00007fecd3284890> (NoMethodError)
```

@jrafanie

**Comment by jrafanie** [comment]
fun!

**Comment by Fryguy** [comment]
correction...the specs don't fail though...

**Comment by djberg96** [comment]
Yep, I see the same thing locally.

Ruby 2.6.5 on Catalina, btw.
